# Generated by Django 4.2.7 on 2023-11-10 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perevalapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coord',
            options={'verbose_name': 'Координаты', 'verbose_name_plural': 'Координаты'},
        ),
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'Изображения', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterModelOptions(
            name='level',
            options={'verbose_name': 'Уровень сложности перевала', 'verbose_name_plural': 'Уровни сложности перевала'},
        ),
        migrations.AlterModelOptions(
            name='pereval',
            options={'verbose_name': 'Перевал', 'verbose_name_plural': 'Перевалы'},
        ),
    ]
