# Generated by Django 4.2.7 on 2023-11-12 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perevalapp', '0002_alter_coord_options_alter_images_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='pereval_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='perevalapp.pereval'),
        ),
    ]
